/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastPodcastIdIndexRouteImport } from './routes/podcast/$podcastId/index'
import { Route as PodcastPodcastIdEpisodeEpisodeIdRouteImport } from './routes/podcast/$podcastId/episode/$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastPodcastIdIndexRoute = PodcastPodcastIdIndexRouteImport.update({
  id: '/podcast/$podcastId/',
  path: '/podcast/$podcastId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastPodcastIdEpisodeEpisodeIdRoute =
  PodcastPodcastIdEpisodeEpisodeIdRouteImport.update({
    id: '/podcast/$podcastId/episode/$episodeId',
    path: '/podcast/$podcastId/episode/$episodeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/podcast/$podcastId/': typeof PodcastPodcastIdIndexRoute
  '/podcast/$podcastId/episode/$episodeId': typeof PodcastPodcastIdEpisodeEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/podcast/$podcastId': typeof PodcastPodcastIdIndexRoute
  '/podcast/$podcastId/episode/$episodeId': typeof PodcastPodcastIdEpisodeEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/podcast/$podcastId/': typeof PodcastPodcastIdIndexRoute
  '/podcast/$podcastId/episode/$episodeId': typeof PodcastPodcastIdEpisodeEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/podcast/$podcastId/' | '/podcast/$podcastId/episode/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/podcast/$podcastId' | '/podcast/$podcastId/episode/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/podcast/$podcastId/'
    | '/podcast/$podcastId/episode/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodcastPodcastIdIndexRoute: typeof PodcastPodcastIdIndexRoute
  PodcastPodcastIdEpisodeEpisodeIdRoute: typeof PodcastPodcastIdEpisodeEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$podcastId/': {
      id: '/podcast/$podcastId/'
      path: '/podcast/$podcastId'
      fullPath: '/podcast/$podcastId/'
      preLoaderRoute: typeof PodcastPodcastIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$podcastId/episode/$episodeId': {
      id: '/podcast/$podcastId/episode/$episodeId'
      path: '/podcast/$podcastId/episode/$episodeId'
      fullPath: '/podcast/$podcastId/episode/$episodeId'
      preLoaderRoute: typeof PodcastPodcastIdEpisodeEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodcastPodcastIdIndexRoute: PodcastPodcastIdIndexRoute,
  PodcastPodcastIdEpisodeEpisodeIdRoute: PodcastPodcastIdEpisodeEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
