/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PotcastIdIndexRouteImport } from './routes/$potcastId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PotcastIdIndexRoute = PotcastIdIndexRouteImport.update({
  id: '/$potcastId/',
  path: '/$potcastId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$potcastId/': typeof PotcastIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$potcastId': typeof PotcastIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$potcastId/': typeof PotcastIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$potcastId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$potcastId'
  id: '__root__' | '/' | '/$potcastId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PotcastIdIndexRoute: typeof PotcastIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$potcastId/': {
      id: '/$potcastId/'
      path: '/$potcastId'
      fullPath: '/$potcastId/'
      preLoaderRoute: typeof PotcastIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PotcastIdIndexRoute: PotcastIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
