/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastPotcastIdIndexRouteImport } from './routes/podcast/$potcastId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastPotcastIdIndexRoute = PodcastPotcastIdIndexRouteImport.update({
  id: '/podcast/$potcastId/',
  path: '/podcast/$potcastId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/podcast/$potcastId/': typeof PodcastPotcastIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/podcast/$potcastId': typeof PodcastPotcastIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/podcast/$potcastId/': typeof PodcastPotcastIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/podcast/$potcastId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/podcast/$potcastId'
  id: '__root__' | '/' | '/podcast/$potcastId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodcastPotcastIdIndexRoute: typeof PodcastPotcastIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$potcastId/': {
      id: '/podcast/$potcastId/'
      path: '/podcast/$potcastId'
      fullPath: '/podcast/$potcastId/'
      preLoaderRoute: typeof PodcastPotcastIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodcastPotcastIdIndexRoute: PodcastPotcastIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
